runtime: python312
entrypoint:  gunicorn -b :$PORT poker.wsgi

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
env_variables:
   APPENGINE_URL: capstone-poker.ue.r.appspot.com
   DATABASE_URL: mysql://root:3~9L3tzOA9f*6@34.174.50.236:3306/pokerdatabase
   DJANGO_SECRET_KEY: django-insecure-$rgg8x6g$^tr%b0@00o=6of)0ygh8!li_f1f&=ako3wtp2!ch+
   DEBUGV: True   


    