services:
  gcloud:
    image: google/cloud-sdk:latest
    volumes:
      - gcp-creds:/creds
      - .:/Capstone_Poker_Django
    working_dir: /Capstone_Poker_Django
    environment:
      - CLOUDSDK_CONFIG=/creds

volumes:
  gcp-creds: