BEGIN;
--
-- Create model Bot
--
CREATE TABLE "poker_bot" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(255) NOT NULL, "price" numeric(5, 2) NOT NULL, "specs" varchar(100) NOT NULL);
COMMIT;
