# Generated by Django 5.1.5 on 2025-03-24 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('Bot_File', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'BasePokerBots',
            },
        ),
        migrations.CreateModel(
            name='TournamentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateRun', models.DateField(auto_now_add=True)),
                ('Notes', models.TextField()),
                ('NumberofPlayers', models.IntegerField()),
                ('NumberofGames', models.IntegerField()),
                ('Visible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'TournamentData',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('Bot_File', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'StudentPokerBots',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberOfRounds', models.IntegerField()),
                ('NumberOfWins', models.IntegerField()),
                ('BotID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.studentbot')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('TournamentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.tournamentdata')),
            ],
            options={
                'db_table': 'Tournament',
            },
        ),
    ]
