# Generated by Django 5.1.5 on 2025-03-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentbot',
            old_name='Bot_User',
            new_name='user',
        ),
    ]
