# Generated by Django 5.1.5 on 2025-04-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentdata',
            name='closing_bot',
            field=models.CharField(blank=True, help_text='Which bot caused this tournament to abort early, if any.', max_length=100, null=True),
        ),
    ]
