# Generated by Django 5.1.5 on 2025-03-20 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_profile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateRun', models.DateField(auto_now_add=True)),
                ('Notes', models.CharField(max_length=140)),
                ('NumberofPlayers', models.IntegerField()),
                ('Visible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'TournamentData',
            },
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberOfRounds', models.IntegerField()),
                ('NumberOfWins', models.IntegerField()),
                ('BotID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.studentbot')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Tournaments',
            },
        ),
    ]
