# Generated by Django 5.1.5 on 2025-03-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_rename_bot_user_studentbot_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basebot',
            old_name='Bot_Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='studentbot',
            old_name='Bot_Name',
            new_name='name',
        ),
    ]
