# Generated by Django 4.2.11 on 2025-02-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_alter_bot_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_integer_field', models.BigIntegerField()),
                ('boolean_field', models.BooleanField(default=False)),
                ('char_field', models.CharField(max_length=255)),
                ('date_field', models.DateField()),
                ('date_time_field', models.DateTimeField()),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=5)),
                ('email_field', models.EmailField(max_length=254)),
                ('float_field', models.FloatField()),
                ('integer_field', models.IntegerField()),
                ('text_field', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Bot',
        ),
    ]
