# Generated by Django 5.1.5 on 2025-03-20 23:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0003_tournamentdata_tournaments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tournaments',
            new_name='Tournament',
        ),
        migrations.AlterModelTable(
            name='tournament',
            table='Tournament',
        ),
    ]
