# Generated by Django 4.2.11 on 2025-02-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0003_bots_delete_bot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bots',
            new_name='Bot',
        ),
    ]
