# Generated by Django 5.1.5 on 2025-03-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0005_tournament_tournamentid_tournamentdata_numberofgames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentdata',
            name='Notes',
            field=models.TextField(),
        ),
    ]
