# Generated by Django 5.1.5 on 2025-03-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='new_field',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
