# Generated by Django 5.1.5 on 2025-03-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0006_alter_tournamentdata_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('Bot_File', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'BasePokerBots',
            },
        ),
    ]