# Generated by Django 5.1.5 on 2025-03-03 01:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0009_alter_bot_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='Bot_Name',
        ),
        migrations.AddField(
            model_name='bot',
            name='Bot_File',
            field=models.FileField(default=1, upload_to='MEDIA_URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
