# Generated by Django 5.1.5 on 2025-03-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0010_remove_bot_bot_name_bot_bot_file_bot_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='Bot_File',
            field=models.FileField(upload_to='poker/bots'),
        ),
    ]
