# Generated by Django 5.1.5 on 2025-03-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0012_remove_profile_new_field_bot_name_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
