# Generated by Django 5.1.5 on 2025-03-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0013_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='Bot_File',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=140),
        ),
    ]
