# Generated by Django 5.1.5 on 2025-03-05 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0014_alter_bot_bot_file_alter_profile_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('Bot_File', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'StudentPokerBots',
            },
        ),
        migrations.RenameModel(
            old_name='Bot',
            new_name='StudentBot',
        ),
        migrations.AlterModelTable(
            name='studentbot',
            table='BasePokerBots',
        ),
    ]
